# MySQL database settings - only required if account-type is sql
mysql:
  host: localhost
  port: 3306
  database: database
  username: root
  password: password

# Account type can be either one ("SQL", "PERSISTENT")
account-type: persistent